apiVersion: v1
kind: ConfigMap
metadata:
  name: nchan-conf
data:
  nchan.conf: |
    upstream my_redis_server {
    nchan_redis_server redis;
  }
  server {
    listen       80;
    server_name  ingame;

    location / {
      proxy_pass http://ingame:8080/;
    }

    # redirect server error pages to the static page /50x.html
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    nchan_channel_group_accounting on;

    location = /sub {
      nchan_subscriber;
      nchan_channel_group 'hoge_group';
      nchan_channel_id 'fuga_id';
      nchan_group_max_subscribers 5;
      nchan_redis_pass my_redis_server;
    }

    location = /pub {
      nchan_publisher;
      nchan_channel_group 'hoge_group';
      nchan_channel_id 'fuga_id';
      nchan_redis_pass my_redis_server;
    }

    location = /group {
      nchan_channel_group hoge_group;
      nchan_group_location;
      nchan_group_max_channels $arg_max_channels;
      nchan_group_max_messages $arg_max_messages;
      nchan_group_max_messages_memory $arg_max_messages_mem;
      nchan_group_max_messages_disk $arg_max_messages_disk;
      nchan_group_max_subscribers $arg_max_subs;
      nchan_redis_pass my_redis_server;
    }
  }
