apiVersion: v1
kind: ConfigMap
metadata:
  name: nchan-conf
  namespace: himo-ingame
data:
  default.conf: |
    upstream my_redis_server {
      nchan_redis_server redis;
    }
    server {
      listen       80;
      server_name  ingame;

      location / {
        proxy_pass http://ingame:8080/;
      }

      # redirect server error pages to the static page /50x.html
      #
      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
          root   /usr/share/nginx/html;
      }

      nchan_channel_group_accounting on;

      # /sub?channel_id=hogehoge&player_num=4 の形式で使う
      location = /sub {
        nchan_subscriber;
        nchan_channel_group $arg_channel_id;
        nchan_channel_id $arg_channel_id;
        nchan_group_max_subscribers $arg_player_num;
        nchan_redis_pass my_redis_server;
      }

      # /pub?channel_id=hogehoge の形式で使う
      location = /pub {
        nchan_publisher;
        nchan_channel_group $arg_channel_id;
        nchan_channel_id $arg_channel_id;
        nchan_redis_pass my_redis_server;
      }

      # /group?channel_id=hogehoge の形式で使う
      location = /group {
        nchan_channel_group $arg_channel_id;
        nchan_group_location;
        nchan_group_max_channels 1;
        nchan_redis_pass my_redis_server;
      }
    }
