apiVersion: v1
kind: Service
metadata:
  name: {{ include "outgame.fullname" . }}
  labels:
    {{- include "outgame.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5502
      protocol: TCP
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "outgame.selectorLabels" . | nindent 4 }}
