apiVersion: v1
kind: Service
metadata:
  name: {{ include "ingame.fullname" . }}
  labels:
    {{- include "ingame.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    {{- include "ingame.selectorLabels" . | nindent 4 }}
