
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-db
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS himo;
    USE himo;
    DROP TABLE IF EXISTS themes;
    CREATE TABLE themes
    (
      id           BIGINT NOT NULL PRIMARY KEY,
      sentence     VARCHAR(100) NOT NULL
    );
    INSERT INTO themes (id, sentence) VALUES
    (1, '身につけていると役立つスキル'),
    (2, '流行っているアーティスト'),
    (3, '強そうな効果音'),
    (4, 'グッとくる仕草'),
    (5, 'ご飯に合うおかず'),
    (6, '言われて傷つく異性からの一言'),
    (7, '一人暮らしをする時に欲しいもの'),
    (8, '雪山に遭難した時に欲しいもの'),
    (9, '人気の給食メニュー'),
    (10, '異性にモテる趣味'),
    (11, 'されたいプロポーズの言葉'),
    (12, '世界的に有名な日本のアニメ'),
    (13, '合コンでウケる職業'),
    (14, '死ぬ直前にしたいこと'),
    (15, '今流行りの言葉'),
    (16, '人気のスナック菓子'),
    (17, '流行っている漫画・アニメ'),
    (18, '人気の観光地'),
    (19, '付き合ってみたい芸能人'),
    (20, '鬼ヶ島に行く前に味方にしたい動物'),
    (21, '友達の家で出てきたら嬉しいお菓子'),
    (22, '親につけて欲しくないキラキラネーム'),
    (23, '1日で100万円を使い切るならすること'),
    (24, '上司に言われるとムカつく一言'),
    (25, '透明人間になったらしたいこと'),
    (26, '正月に食べるもの'),
    (27, '許されそうな遅刻の言い訳'),
    (28, '教育ママが子どもにさせがちな習い事'),
    (29, 'これだけはやめてほしいマナー違反'),
    (30, '女子高生がよく使いそうな絵文字'),
    (31, '人気女性インフルエンサーの特徴'),
    (32, '意識高い系の特徴'),
    (33, '法律が無くなったらやりたいこと'),
    (34, '寿命が伸びそうな生活習慣'),
    (35, '言われて嬉しい言葉'),
    (36, '会議中に言ってはいけない一言'),
    (37, '人気の告白のシチュエーション'),
    (38, '無人島で役立ちそうな超能力'),
    (39, '手に入れたい超能力'),
    (40, '人生で一度は経験してみたいこと'),
    (41, '流行りの技術'),
    (42, '人気なプログラミング言語'),
    (43, '初心者におすすめのプログラミング言語'),
    (44, '人気のエディタ'),
    (45, 'よく使うLinuxコマンド'),
    (46, '人気のLinuxコマンド'),
    (47, '技術力の高いIT企業'),
    (48, 'よく使うポート番号'),
    (49, '人気のフレームワーク'),
    (50, 'チーム開発で大切なこと'),
    (51, '有名な技術書'),
    (52, '便利なGUIツール'),
    (53, 'プログラミング中で楽しい瞬間'),
    (54, '辛いバグ'),
    (55, '人気のクラウドサービス'),
    (56, '開発が盛んなOSS'),
    (57, '人気のデータベース'),
    (58, 'よく使うDocker image'),
    (59, '人気のCIツール'),
    (60, '人気のOS'),
    (61, 'エンジニアに人気の趣味'),
    (62, '人気のライブラリ'),
    (63, '強いエンジニアの共通点'),
    (64, '強いエンジニア'),
    (65, 'よく使うgitコマンド'),
    (66, 'エンジニアに人気のWikiツール'),
    (67, 'エンジニアに人気のゲーム'),
    (68, 'エンジニアに多い出身学部・学科'),
    (69, 'エンジニアの良くないところ'),
    (70, 'エンジニアの良いところ'),
    (71, 'エンジニアの好きな飲み物'),
    (72, 'エンジニアが恋人に求めるであろうポイント'),
    (73, 'すぐに伸びそうな人の特徴'),
    (74, 'エンジニアがよく着る服'),
    (75, 'これから来そうな言語'),
    (76, 'これから来そうなサービス'),
    (77, 'これから来そうな技術'),
    (78, '先輩エンジニアに言われて嬉しい言葉'),
    (79, 'エンジニアのデスクに必ずあるもの'),
    (80, '初心者の頃やりがちなミス'),
    (81, 'お持ち帰りの誘い文句'),
    (82, 'チラ見えしたらドキッとする部位'),
    (83, '行為中に興奮する異性からの言葉'),
    (84, '童貞がイチコロになる服装'),
    (85, '初めての行為でやりがちなミス'),
    (86, '人気なAV女優といえば'),
    (87, 'ピロートークの一言目といえば'),
    (88, '風俗あるある'),
    (89, 'エロい女にありがちなLINEのトプ画'),
    (90, 'ヤリモク男の特徴'),
    (91, '実はエロい女の特徴'),
    (92, '経験人数が少なさそうな男の特徴'),
    (93, '行為が上手い男の特徴'),
    (94, 'なんかエロい擬音語'),
    (95, '女遊びする男の部屋の特徴'),
    (96, '相手にしてもらいたいコスプレ'),
    (97, '手に入れたいエロい超能力'),
    (98, '浮気癖のある人の特徴'),
    (99, '日常生活で男性にエロいと感じる瞬間'),
    (100, '日常生活で女性にエロいと感じる瞬間'),
    (101, 'すぐに彼氏が入れ替わる女の特徴'),
    (102, 'セフレに重視する点'),
    (103, 'ゆるふわビッチが好きなブランド'),
    (104, '実は性欲が強い男の特徴'),
    (105, 'バレたくない性癖'),
    (106, '抱かれたい男性芸能人'),
    (107, '抱きたい女性芸能人'),
    (108, '好きなAVのカテゴリー'),
    (109, 'おもちゃに使えそうな食べ物'),
    (110, '一夜を共にしたい相手の国籍'),
    (111, '興奮するシチュエーション'),
    (112, '男性に人気のカップ数'),
    (113, 'エロい人が多い部活'),
    (114, '人気のフェチ'),
    (115, 'セクシーと感じる仕草'),
    (116, '行為に至るまでの理想のシチュエーション'),
    (117, 'ムラムラするとき'),
    (118, '一度はやってみたい場所'),
    (119, 'それまで満々だったヤる気が失せる時'),
    (120, '行為中に幸せを感じる時'),
    (121, 'されると嬉しい告白の言葉'),
    (122, '結婚したらショックな芸能人'),
    (123, '晩御飯に出てきたら嬉しいおかず'),
    (124, '有名なYouTubeチャンネル'),
    (125, '演奏できるとカッコいい楽器'),
    (126, '生活に欠かせない電化製品'),
    (127, '宝くじに当たったら最初に買いたいもの'),
    (128, '身につけておくべきマナー'),
    (129, '夏に聴きたい曲'),
    (130, '遭遇したら怖い動物'),
    (131, 'コーラに合う食べ物'),
    (132, 'ビールに合うおつまみ'),
    (133, '子供の頃に夢中になったアニメ'),
    (134, '好きな人に言われたいひとこと'),
    (135, 'バーベキューに欠かせない食材'),
    (136, '革新的な発明'),
    (137, '有名な歴史上の出来事'),
    (138, '中学・高校でモテる人の特徴'),
    (139, 'コーヒーと一緒に食べたいスイーツ'),
    (140, '強そうな漢字'),
    (141, 'スマホの便利なアプリ'),
    (142, '一番欲しいドラえもんの道具'),
    (143, '絶対に許せない嘘'),
    (144, 'ハロウィンで仮装したいキャラ'),
    (145, 'よくある結婚相手の条件'),
    (146, '女子力の高い持ち物'),
    (147, '外国人に胸を張って紹介したい日本食'),
    (148, '宇宙旅行に持っていきたいもの'),
    (149, '親が子供に見せたくないテレビ番組'),
    (150, 'かっこいい名前・苗字'),
    (151, '一日だけならなりたい職業'),
    (152, 'ゾンビと戦う時に持っていたいもの'),
    (153, 'リラックスできる場所'),
    (154, '未来のスマホに欲しい機能'),
    (155, '子供の頃に憧れるもの'),
    (156, '怖いもの'),
    (157, 'テンションが上がるもの・こと'),
    (158, '一生に一度は体験してみたいこと'),
    (159, '人気の学校給食'),
    (160, 'パーティに欲しいご馳走'),
    (161, 'おしゃれな部屋のアイテム'),
    (162, '人生で一度きりのイベント'),
    (163, '高価なもの'),
    (164, 'お金持ちが飼ってそうなペット'),
    (165, '体に良さそうな食材'),
    (166, '頭が良い人の特徴'),
    (167, '人間が生きる上で必要なもの・こと'),
    (168, '一杯目に頼みたくなるお酒'),
    (169, '恋人にしてほしくない行為'),
    (170, '絶対にやりたくない仕事'),
    (171, '有名な名言'),
    (172, '遭難した時に一緒にいると心強い人'),
    (173, '友達に会ったら気まずいシチュエーション'),
    (174, '喧嘩が強そうな名字'),
    (175, '小さい頃にもっとやっておけばよかったこと'),
    (176, '治安が悪そうな国'),
    (177, '無人島で最初にすること'),
    (178, '習得したいポケモンの技'),
    (179, '誕生日プレゼントに欲しいもの'),
    (180, '戦闘能力の高そうな部活');
