apiVersion: v1
kind: Service
metadata:
  name: {{ include "outgame-db.fullname" . }}
  labels:
    {{- include "outgame-db.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3306
      protocol: TCP
  selector:
    {{- include "outgame-db.selectorLabels" . | nindent 4 }}
